//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp_WebEventPoster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> EventCategoryID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> TransUpdateDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual Country Country { get; set; }
        public virtual Event Event { get; set; }
        public virtual EventCategory EventCategory { get; set; }
    }
}
